### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ghost** [gamehelp16/now-clocking#1]
When any of the scripts were running, they made my PC really laggy. 

Changing "update_interval" from 0.01 to 1 lowered the overall consumption to almost nothing and kept the same performance.

**Comment by gamehelp16** [comment]
Yeah you're right, at first I set it to 1 but decided to change it because the seconds on the clock widget don't sync with the seconds on the top bar which annoys me a little :d

I will change it once I'm not on mobile, thank you!

**Comment by gamehelp16** [comment]
I have updated the code.
