### ISSUE TITLE
unmaintained?

### ISSUE THREAD

**Issue by foxfirecodes** [gamehelp16/now-clocking#5]
hey! just wanted to say i LOVE your project, been using it for years. however, over time, conky config formats and options and such have changed, various DE/WM/compositor setups have weirdness, and so this script no longer works quite right out of the box.

I've got my own fork over at [Rayzr522/now-clocking](https://github.com/Rayzr522/now-clocking) where I've cleaned it up and it basically just works out of the box now on any DE/WM/compositor combo (from my testing at least), but I was wondering if you plan on maintaining this upstream repo at all anymore?

would love to see this project come back to life. this is such a nice touch to add to any Linux setup, and I've got it installed on all my machines :)

**Comment by foxfirecodes** [comment]
if you don't intend to maintain this anymore, would it be possible to consider adding a header at the top of the README saying this is unmaintained and linking to my maintained fork?

**Comment by gamehelp16** [comment]
As of now I don't have any plans to maintain the repo, but thank you for your enthusiasm on the project and for making a fork! I'll add a link to your fork on the readme.

**Comment by foxfirecodes** [comment]
thanks!! and thank you again for your contributions to the open source community!
